create table if not exists sync_profiles (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    profile_type varchar(32) not null,
    source_path varchar(2000),
    target_path varchar(2000),
    include_patterns varchar(8000),
    exclude_patterns varchar(8000),
    allow_target_inside_source boolean not null,
    last_successful_dry_run_hash varchar(255),
    last_successful_dry_run_at timestamp(6) with time zone
);

create table if not exists replacement_rules (
    id bigint generated by default as identity primary key,
    profile_id bigint not null,
    rule_id varchar(255) not null,
    search_value varchar(4000) not null,
    replacement_value varchar(4000) not null,
    case_sensitive boolean not null,
    regex boolean not null,
    enabled boolean not null,
    sort_order integer not null,
    constraint fk_replacement_rules_profile
        foreign key (profile_id) references sync_profiles(id)
);

create table if not exists replacement_rule_apply_targets (
    replacement_rule_id bigint not null,
    apply_target varchar(32) not null,
    primary key (replacement_rule_id, apply_target),
    constraint fk_replacement_apply_targets_rule
        foreign key (replacement_rule_id) references replacement_rules(id)
);

create table if not exists sensitive_term_rules (
    id bigint generated by default as identity primary key,
    profile_id bigint not null,
    rule_id varchar(255) not null,
    case_sensitive boolean not null,
    enabled boolean not null,
    sort_order integer not null,
    constraint fk_sensitive_term_rules_profile
        foreign key (profile_id) references sync_profiles(id)
);

create table if not exists sensitive_term_values (
    sensitive_term_rule_id bigint not null,
    value_order integer not null,
    term_value varchar(4000) not null,
    primary key (value_order, sensitive_term_rule_id),
    constraint fk_sensitive_term_values_rule
        foreign key (sensitive_term_rule_id) references sensitive_term_rules(id)
);

create table if not exists sync_runs (
    id bigint generated by default as identity primary key,
    profile_id bigint,
    profile_name varchar(255) not null,
    profile_type varchar(32) not null,
    dry_run boolean not null,
    started_at timestamp(6) with time zone,
    ended_at timestamp(6) with time zone,
    status varchar(255) not null,
    config_hash varchar(255),
    source_root varchar(2000),
    target_root varchar(2000),
    redaction_values_json clob,
    constraint fk_sync_runs_profile
        foreign key (profile_id) references sync_profiles(id)
);

create table if not exists sync_report_entries (
    id bigint generated by default as identity primary key,
    run_id bigint not null,
    source_path varchar(2000),
    target_path varchar(2000),
    source_relative_path varchar(2000),
    target_relative_path varchar(2000),
    operation_type varchar(32) not null,
    operation_status varchar(32) not null,
    path_replacement_counts_json clob,
    content_replacement_counts_json clob,
    rule_ids_csv varchar(2000),
    leak_findings_json clob,
    error_message clob,
    constraint fk_sync_report_entries_run
        foreign key (run_id) references sync_runs(id)
);

create index if not exists idx_replacement_rules_profile_sort
    on replacement_rules(profile_id, sort_order);

create index if not exists idx_sensitive_term_rules_profile_sort
    on sensitive_term_rules(profile_id, sort_order);

create index if not exists idx_sync_runs_started_at
    on sync_runs(started_at desc);

create index if not exists idx_sync_runs_profile
    on sync_runs(profile_id);

create index if not exists idx_sync_report_entries_run
    on sync_report_entries(run_id);
